name: gerenciador_distribuidora
description: "MVP Desktop para distribuidora de bebidas (estoque FEFO, vendas e faturamento simulado)"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Navegação e estado
  go_router: ^14.2.0
  provider: ^6.1.2

  # Banco de dados (Desktop)
  drift: ^2.17.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  sqflite:
  path_provider: ^2.1.3
  path: ^1.9.0

  # Utilidades
  intl: ^0.19.0
  csv: ^6.0.0
  collection: ^1.18.0
  parse_server_sdk_flutter: ^6.0.0

  pdf: ^3.10.7
  printing: ^5.12.0
  file_picker: ^8.0.0

  window_manager: ^0.4.2

  # UI helpers
  flutter_hooks: ^0.20.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  drift_dev: ^2.17.0

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
